directo: directo.cpp
	g++ directo.cpp -o directo 

dyv: dyv.cpp
	g++ dyv.cpp -o dyv 

generadorCasos: generadorCasos.cpp
	g++ generadorCasos.cpp -o generadorCasos 


clean:
	rm -f directo dyv generadorCasos
